// flow-typed signature: 87f94185675c814935300a97c96775f3
// flow-typed version: <<STUB>>/apollo-client-preset_v^1.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-client-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-client-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-client-preset/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-client-preset/lib/index.js' {
  declare module.exports: $Exports<'apollo-client-preset/lib/index'>;
}
