// flow-typed signature: 4d3cf364e604e1a5cfcad0466db671c7
// flow-typed version: <<STUB>>/redux-session_v^1.0.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-session/dist/index' {
  declare module.exports: any;
}

declare module 'redux-session/rollup.config' {
  declare module.exports: any;
}

declare module 'redux-session/src/adapters/cookieStorage' {
  declare module.exports: any;
}

declare module 'redux-session/src/adapters/localStorage' {
  declare module.exports: any;
}

declare module 'redux-session/src/index' {
  declare module.exports: any;
}

declare module 'redux-session/src/utils' {
  declare module.exports: any;
}

declare module 'redux-session/test/createSession' {
  declare module.exports: any;
}

declare module 'redux-session/test/localStorage' {
  declare module.exports: any;
}

declare module 'redux-session/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-session/dist/index.js' {
  declare module.exports: $Exports<'redux-session/dist/index'>;
}
declare module 'redux-session/rollup.config.js' {
  declare module.exports: $Exports<'redux-session/rollup.config'>;
}
declare module 'redux-session/src/adapters/cookieStorage.js' {
  declare module.exports: $Exports<'redux-session/src/adapters/cookieStorage'>;
}
declare module 'redux-session/src/adapters/localStorage.js' {
  declare module.exports: $Exports<'redux-session/src/adapters/localStorage'>;
}
declare module 'redux-session/src/index.js' {
  declare module.exports: $Exports<'redux-session/src/index'>;
}
declare module 'redux-session/src/utils.js' {
  declare module.exports: $Exports<'redux-session/src/utils'>;
}
declare module 'redux-session/test/createSession.js' {
  declare module.exports: $Exports<'redux-session/test/createSession'>;
}
declare module 'redux-session/test/localStorage.js' {
  declare module.exports: $Exports<'redux-session/test/localStorage'>;
}
declare module 'redux-session/test/utils.js' {
  declare module.exports: $Exports<'redux-session/test/utils'>;
}
