// @flow
import type MenuAction from '../reducers/menu';

// Add future action types as union type
export type Action = MenuAction;
export type Dispatch = (action: Action) => void;

export const ADD_SAMPLE_RANGE_FORM_ERROR = 'ADD_SAMPLE_RANGE_FORM_ERROR';
export const CLOSE_STRUCTURE = 'CLOSE_STRUCTURE';
export const DB_CHANGED = 'DB_CHANGED';
export const DISMISS_APPLICATION_ERROR = 'DISMISS_APPLICATION_ERROR';
export const DISMISS_CONNECTION_ERROR = 'DISMISS_CONNECTION_ERROR';
export const GET_USERINFOS = 'GET_USERINFOS';
export const OPEN_CLOSE_MENU = 'OPEN_CLOSE_MENU';
export const OPEN_STRUCTURE = 'OPEN_STRUCTURE';
export const REFRESH_USER_TOKEN = 'REFRESH_USER_TOKEN';
export const REOPEN_STRUCTURES = 'REOPEN_STRUCTURES';
export const RESET_SAMPLE_RANGE_FORM = 'RESET_SAMPLE_RANGE_FORM';
export const SET_APPLICATION_ERROR = 'SET_APPLICATION_ERROR';
export const SET_CONNECTION_ERROR = 'SET_CONNECTION_ERROR';
export const SET_FORM_MODE = 'SET_FORM_MODE';
export const SET_MENU_TYPE = 'SET_MENU_TYPE';
export const SET_SAMPLE_RANGE_FORM_FIELD = 'SET_SAMPLE_RANGE_FORM_FIELD';
export const TOGGLE_REFETCH_QUERIES = 'TOGGLE_REFETCH_QUERIES';
export const UPDATE_SAMPLE_RANGE_FORM_FIELD = 'UPDATE_SAMPLE_RANGE_FORM_FIELD';
export const UPDATE_SAMPLE_RANGE_FORM_FIELD_FOR_ADD =
  'UPDATE_SAMPLE_RANGE_FORM_FIELD_FOR_ADD';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_IN_ERROR = 'USER_LOGGED_IN_ERROR';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const UPDATE_SAMPLE_RANGE_FORM_NOTES_ACTIONS =
  'UPDATE_SAMPLE_RANGE_FORM_NOTES_ACTIONS';
